//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccionesCompetencia
    {
        public int AccionesCompetencia_Id { get; set; }
        public string AccionesCompetencia_Division { get; set; }
        public string AccionesCompetencia_Canal { get; set; }
        public string AccionesCompetencia_Descripcion { get; set; }
        public string AccionesCompetencia_Precio { get; set; }
        public string AccionesCompetencia_PrecioOferta { get; set; }
        public string AccionesCompetencia_Observacion { get; set; }
        public string AccionesCompetencia_Colaborador { get; set; }
    }
}
