//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class bi_project
    {
        public int id { get; set; }
        public string priority { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> assigned { get; set; }
        public Nullable<System.DateTime> corrected { get; set; }
        public Nullable<System.DateTime> closed { get; set; }
    }
}
