//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class bi_sales
    {
        public int id { get; set; }
        public Nullable<System.DateTime> salesdate { get; set; }
        public string region { get; set; }
        public string category { get; set; }
        public string product { get; set; }
        public string customer { get; set; }
        public int qtysold { get; set; }
        public double pricein { get; set; }
        public Nullable<decimal> priceout { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<decimal> sales { get; set; }
        public Nullable<decimal> profit { get; set; }
    }
}
