//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class bi_salary_survey
    {
        public int id { get; set; }
        public Nullable<int> salary_local { get; set; }
        public string currency { get; set; }
        public Nullable<decimal> salary_usd { get; set; }
        public string job_type { get; set; }
        public string work_hours_day { get; set; }
        public Nullable<int> years_experience { get; set; }
        public string country { get; set; }
        public string continent { get; set; }
        public Nullable<int> code_hours { get; set; }
        public Nullable<decimal> ppp_factor { get; set; }
        public Nullable<decimal> salary_usd_ppp { get; set; }
    }
}
