//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryPlanVisita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoryPlanVisita()
        {
            this.CategoryPlanVisita1 = new HashSet<CategoryPlanVisita>();
        }
    
        public short PlanVisitaCatId { get; set; }
        public string PlanVisitaCatName { get; set; }
        public Nullable<short> PlanVisitaCatParentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryPlanVisita> CategoryPlanVisita1 { get; set; }
        public virtual CategoryPlanVisita CategoryPlanVisita2 { get; set; }
    }
}
