//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public int Empresa_Id { get; set; }
        public string Empresa_Nombre { get; set; }
        public System.DateTime Empresa_FechaCreacion { get; set; }
        public System.DateTime Empresa_FechaLastUpdate { get; set; }
    }
}
