//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class entradadeposito
    {
        public int EntradaDepositoId { get; set; }
        public System.DateTime EntradaDepositoFecha { get; set; }
        public int OcDocEntry { get; set; }
        public string EntradaDepositoUser { get; set; }
        public int EntradaDepositoNroEntrada { get; set; }
    }
}
