//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class entradadepositodetalle
    {
        public int EntradaDepositoId { get; set; }
        public int OC1LineNum { get; set; }
        public decimal PPDetLinRecibida { get; set; }
        public string DLote { get; set; }
        public System.DateTime DVencimiento { get; set; }
        public short Bultos { get; set; }
        public byte[] COA { get; set; }
    }
}
