//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class JefeVentas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JefeVentas()
        {
            this.JefeVentasCanal = new HashSet<JefeVentasCanal>();
            this.Notificacion = new HashSet<Notificacion>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int JefeVentas_Id { get; set; }
        public string JefeVentas_Nombre { get; set; }
        public int Division_Id { get; set; }
        public string JefeVentas_Mail { get; set; }
        public System.DateTime JefeVentas_FechaCreacion { get; set; }
        public System.DateTime JefeVentas_FechaLastUpdate { get; set; }
    
        public virtual Division Division { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JefeVentasCanal> JefeVentasCanal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notificacion> Notificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
