//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class JefeVenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JefeVenta()
        {
            this.JefeVentasCanals = new HashSet<JefeVentasCanal>();
            this.Notificacions = new HashSet<Notificacion>();
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public int JefeVentas_Id { get; set; }
        public string JefeVentas_Nombre { get; set; }
        public int Division_Id { get; set; }
        public string JefeVentas_Mail { get; set; }
        public System.DateTime JefeVentas_FechaCreacion { get; set; }
        public System.DateTime JefeVentas_FechaLastUpdate { get; set; }
    
        public virtual Division Division { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JefeVentasCanal> JefeVentasCanals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notificacion> Notificacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
