//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationHistory
    {
        public System.Guid LocationHistory1 { get; set; }
        public System.DateTime LocationHistoryFecha { get; set; }
        public string LocationHistoryGeolocation { get; set; }
        public string LocationHistoryUser { get; set; }
        public System.DateTime LocationHistoryTime { get; set; }
        public string LocationHistoryDescription { get; set; }
        public decimal LocationHistoryPrecision { get; set; }
        public decimal LocationHistoryHeading { get; set; }
        public decimal LocationHistorySpeed { get; set; }
    }
}
