//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationHistory
    {
        public System.Guid LocationHistory1 { get; set; }
        public System.DateTime LocationHistoryFecha { get; set; }
        public string LocationHistoryGeolocation { get; set; }
        public string LocationHistoryUser { get; set; }
        public System.DateTime LocationHistoryTime { get; set; }
        public string LocationHistoryDescription { get; set; }
        public decimal LocationHistoryPrecision { get; set; }
        public decimal LocationHistoryHeading { get; set; }
        public decimal LocationHistorySpeed { get; set; }
    }
}
