//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mobiliario
    {
        public int Mobiliario_Id { get; set; }
        public int Usuario_Id { get; set; }
        public int Marca_Id { get; set; }
        public int TipoMueble_Id { get; set; }
        public System.DateTime Mobiliario_FechaCarga { get; set; }
        public int Mobiliario_Cantidad { get; set; }
        public bool Mobiliario_LucesEncendidas { get; set; }
        public string Mobiliario_Observacion { get; set; }
    
        public virtual Marcas Marcas { get; set; }
        public virtual TipoMueble TipoMueble { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
