//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motivo
    {
        public int Motivo_Id { get; set; }
        public string Motivo_Descripcion { get; set; }
        public System.DateTime Motivo_FechaCreacion { get; set; }
        public System.DateTime Motivo_FechaLastUpdate { get; set; }
    }
}
