//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificacion
    {
        public int Notificacion_Id { get; set; }
        public string Notificacion_Descripcion { get; set; }
        public System.DateTime Notificacion_Fecha { get; set; }
        public int JefeVentas_Id { get; set; }
        public string Estado { get; set; }
    
        public virtual JefeVentas JefeVentas { get; set; }
    }
}
