//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificacion
    {
        public int Notificacion_Id { get; set; }
        public string Notificacion_Descripcion { get; set; }
        public System.DateTime Notificacion_Fecha { get; set; }
        public int JefeVentas_Id { get; set; }
        public string Estado { get; set; }
    
        public virtual JefeVentas JefeVentas { get; set; }
    }
}
