//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjetivoVisita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ObjetivoVisita()
        {
            this.PlanSemanalDetalle = new HashSet<PlanSemanalDetalle>();
            this.PlanVisita = new HashSet<PlanVisita>();
        }
    
        public int ObjetivoVisita_Id { get; set; }
        public string ObjetivoVisita_Descripcion { get; set; }
        public System.DateTime ObjetivoVisita_FechaCreacion { get; set; }
        public System.DateTime ObjetivoVisita_FechaLastUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanSemanalDetalle> PlanSemanalDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanVisita> PlanVisita { get; set; }
    }
}
