//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Periodo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Periodo()
        {
            this.PeriodoDet = new HashSet<PeriodoDet>();
        }
    
        public string PeriodoCodigo { get; set; }
        public short PeriodoAno { get; set; }
        public short PeriodoMes { get; set; }
        public System.DateTime PeriodoFechaInicial { get; set; }
        public System.DateTime PeriodoFechaFinal { get; set; }
        public string PeriodoDescripcion { get; set; }
        public string PeriodoEstado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PeriodoDet> PeriodoDet { get; set; }
    }
}
