//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodoDet
    {
        public string PeriodoCodigo { get; set; }
        public string PeriodoSemana { get; set; }
        public System.DateTime PeriodoSemanaFechaInicial { get; set; }
        public System.DateTime PeriodoSemanaFechaFin { get; set; }
    
        public virtual Periodo Periodo { get; set; }
    }
}
