//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Periodo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Periodo()
        {
            this.PeriodoDets = new HashSet<PeriodoDet>();
        }
    
        public string PeriodoCodigo { get; set; }
        public short PeriodoAno { get; set; }
        public short PeriodoMes { get; set; }
        public System.DateTime PeriodoFechaInicial { get; set; }
        public System.DateTime PeriodoFechaFinal { get; set; }
        public string PeriodoDescripcion { get; set; }
        public string PeriodoEstado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PeriodoDet> PeriodoDets { get; set; }
    }
}
