//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PLAN_VISITAEntities : DbContext
    {
        public PLAN_VISITAEntities()
            : base("name=PLAN_VISITAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Canal> Canal { get; set; }
        public virtual DbSet<CanalSucursal> CanalSucursal { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Division> Division { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<EstadoMotivo> EstadoMotivo { get; set; }
        public virtual DbSet<JefeVentas> JefeVentas { get; set; }
        public virtual DbSet<JefeVentasCanal> JefeVentasCanal { get; set; }
        public virtual DbSet<Motivo> Motivo { get; set; }
        public virtual DbSet<Notificacion> Notificacion { get; set; }
        public virtual DbSet<ObjetivoVisita> ObjetivoVisita { get; set; }
        public virtual DbSet<Periodo> Periodo { get; set; }
        public virtual DbSet<PeriodoDet> PeriodoDet { get; set; }
        public virtual DbSet<PlanAccion> PlanAccion { get; set; }
        public virtual DbSet<PlanSemanal> PlanSemanal { get; set; }
        public virtual DbSet<PlanSemanalDetalle> PlanSemanalDetalle { get; set; }
        public virtual DbSet<PlanSemanalSAP> PlanSemanalSAP { get; set; }
        public virtual DbSet<PlanVisita> PlanVisita { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Sucursal> Sucursal { get; set; }
        public virtual DbSet<Tarea> Tarea { get; set; }
        public virtual DbSet<Task> Task { get; set; }
        public virtual DbSet<Ubicacion> Ubicacion { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<VencimientoProducto> VencimientoProducto { get; set; }
        public virtual DbSet<Vendedor> Vendedor { get; set; }
        public virtual DbSet<VendedorCliente> VendedorCliente { get; set; }
        public virtual DbSet<VendedorClienteSAP> VendedorClienteSAP { get; set; }
        public virtual DbSet<VendedorZona> VendedorZona { get; set; }
        public virtual DbSet<Venta> Venta { get; set; }
        public virtual DbSet<VentaLinea> VentaLinea { get; set; }
        public virtual DbSet<Visita> Visita { get; set; }
        public virtual DbSet<VisitaDual> VisitaDual { get; set; }
        public virtual DbSet<VisitaSAP> VisitaSAP { get; set; }
        public virtual DbSet<Zona> Zona { get; set; }
        public virtual DbSet<ZonaSucursal> ZonaSucursal { get; set; }
        public virtual DbSet<Detalle_Visita> Detalle_Visita { get; set; }
        public virtual DbSet<V_Canales_HBF> V_Canales_HBF { get; set; }
        public virtual DbSet<V_CARTERA_ACTUAL> V_CARTERA_ACTUAL { get; set; }
        public virtual DbSet<V_Cartera_Clientes> V_Cartera_Clientes { get; set; }
        public virtual DbSet<V_CLIENTE_SUCURSAL> V_CLIENTE_SUCURSAL { get; set; }
        public virtual DbSet<V_Clientes_HBF> V_Clientes_HBF { get; set; }
        public virtual DbSet<V_Clientes_Total> V_Clientes_Total { get; set; }
        public virtual DbSet<V_ClientesVenRep> V_ClientesVenRep { get; set; }
        public virtual DbSet<V_Detalle_Visita> V_Detalle_Visita { get; set; }
        public virtual DbSet<V_Dual_Visita> V_Dual_Visita { get; set; }
        public virtual DbSet<V_PLAN_SEMANAL> V_PLAN_SEMANAL { get; set; }
        public virtual DbSet<V_PlanSemCargXDia> V_PlanSemCargXDia { get; set; }
        public virtual DbSet<V_RUTA_DIA> V_RUTA_DIA { get; set; }
        public virtual DbSet<V_RUTA_DIA_NUEVO> V_RUTA_DIA_NUEVO { get; set; }
        public virtual DbSet<V_VDetallePlanSVendedores> V_VDetallePlanSVendedores { get; set; }
        public virtual DbSet<V_Visitas_Detalle> V_Visitas_Detalle { get; set; }
        public virtual DbSet<V_Visitas_Dual> V_Visitas_Dual { get; set; }
        public virtual DbSet<VClienteSAPHBF> VClienteSAPHBF { get; set; }
        public virtual DbSet<VFrecuenciaVendedorCliente> VFrecuenciaVendedorCliente { get; set; }
        public virtual DbSet<VVisitasRealizadas> VVisitasRealizadas { get; set; }
    }
}
