//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PLAN_VISITAEntities : DbContext
    {
        public PLAN_VISITAEntities()
            : base("name=PLAN_VISITAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccionesCompetencia> AccionesCompetencia { get; set; }
        public virtual DbSet<Canal> Canal { get; set; }
        public virtual DbSet<CanalSucursal> CanalSucursal { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Division> Division { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<EstadoMotivo> EstadoMotivo { get; set; }
        public virtual DbSet<JefeVentas> JefeVentas { get; set; }
        public virtual DbSet<JefeVentasCanal> JefeVentasCanal { get; set; }
        public virtual DbSet<Marcas> Marcas { get; set; }
        public virtual DbSet<Mobiliario> Mobiliario { get; set; }
        public virtual DbSet<Motivo> Motivo { get; set; }
        public virtual DbSet<Notificacion> Notificacion { get; set; }
        public virtual DbSet<ObjetivoVisita> ObjetivoVisita { get; set; }
        public virtual DbSet<Periodo> Periodo { get; set; }
        public virtual DbSet<PeriodoDet> PeriodoDet { get; set; }
        public virtual DbSet<PlanAccion> PlanAccion { get; set; }
        public virtual DbSet<PlanSemanal> PlanSemanal { get; set; }
        public virtual DbSet<PlanSemanalDetalle> PlanSemanalDetalle { get; set; }
        public virtual DbSet<PlanSemanalSAP> PlanSemanalSAP { get; set; }
        public virtual DbSet<PlanVisita> PlanVisita { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Puntera> Puntera { get; set; }
        public virtual DbSet<SubMarca> SubMarca { get; set; }
        public virtual DbSet<Sucursal> Sucursal { get; set; }
        public virtual DbSet<Tarea> Tarea { get; set; }
        public virtual DbSet<Task> Task { get; set; }
        public virtual DbSet<TipoMueble> TipoMueble { get; set; }
        public virtual DbSet<Ubicacion> Ubicacion { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<VencimientoProducto> VencimientoProducto { get; set; }
        public virtual DbSet<VencimientoProductoDetalle> VencimientoProductoDetalle { get; set; }
        public virtual DbSet<Vendedor> Vendedor { get; set; }
        public virtual DbSet<VendedorCliente> VendedorCliente { get; set; }
        public virtual DbSet<VendedorClienteSAP> VendedorClienteSAP { get; set; }
        public virtual DbSet<VendedorZona> VendedorZona { get; set; }
        public virtual DbSet<Venta> Venta { get; set; }
        public virtual DbSet<VentaLinea> VentaLinea { get; set; }
        public virtual DbSet<Visita> Visita { get; set; }
        public virtual DbSet<VisitaDual> VisitaDual { get; set; }
        public virtual DbSet<VisitaSAP> VisitaSAP { get; set; }
        public virtual DbSet<Zona> Zona { get; set; }
        public virtual DbSet<ZonaSucursal> ZonaSucursal { get; set; }
    }
}
