//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanSemanal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanSemanal()
        {
            this.PlanSemanalDetalles = new HashSet<PlanSemanalDetalle>();
        }
    
        public int PlanSemanal_Id { get; set; }
        public string PlanSemanal_Periodo { get; set; }
        public int PlanSemanal_NroSemana { get; set; }
        public int Vendedor_Id { get; set; }
        public string PlanSemanal_Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanSemanalDetalle> PlanSemanalDetalles { get; set; }
    }
}
