//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanAccion
    {
        public int PlanAccion_Id { get; set; }
        public string PlanAccion_Analisis { get; set; }
        public string PlanAccion_Descripcion { get; set; }
        public string PlanAccion_Responsable { get; set; }
        public System.DateTime PlanAccion_FechaComp { get; set; }
        public string PlanAccion_Estado { get; set; }
        public System.DateTime PlanAccion_FechaCreacion { get; set; }
        public System.DateTime planAccion_FechaLastUpdate { get; set; }
        public short PlandeVisita { get; set; }
    }
}
