//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PLAN_VISITAEntitiesLectura : DbContext
    {
        public PLAN_VISITAEntitiesLectura()
            : base("name=PLAN_VISITAEntitiesLectura")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Detalle_Visita> Detalle_Visita { get; set; }
        public virtual DbSet<V_CARTERA_ACTUAL> V_CARTERA_ACTUAL { get; set; }
        public virtual DbSet<V_Cartera_Clientes> V_Cartera_Clientes { get; set; }
        public virtual DbSet<V_CLIENTE_SUCURSAL> V_CLIENTE_SUCURSAL { get; set; }
        public virtual DbSet<V_Clientes_HBF> V_Clientes_HBF { get; set; }
        public virtual DbSet<V_Clientes_Total> V_Clientes_Total { get; set; }
        public virtual DbSet<V_ClientesVenRep> V_ClientesVenRep { get; set; }
        public virtual DbSet<V_Detalle_Visita> V_Detalle_Visita { get; set; }
        public virtual DbSet<V_Dual_Visita> V_Dual_Visita { get; set; }
        public virtual DbSet<V_PLAN_SEMANAL> V_PLAN_SEMANAL { get; set; }
        public virtual DbSet<V_RUTA_DIA> V_RUTA_DIA { get; set; }
        public virtual DbSet<V_RUTA_DIA_NUEVO> V_RUTA_DIA_NUEVO { get; set; }
        public virtual DbSet<V_VDetallePlanSVendedores> V_VDetallePlanSVendedores { get; set; }
        public virtual DbSet<V_Visitas_Detalle> V_Visitas_Detalle { get; set; }
        public virtual DbSet<V_Visitas_Dual> V_Visitas_Dual { get; set; }
        public virtual DbSet<VCoberturaVendedor> VCoberturaVendedor { get; set; }
        public virtual DbSet<VFrecuenciaVendedorCliente> VFrecuenciaVendedorCliente { get; set; }
        public virtual DbSet<VNotifCostoBodegaByH> VNotifCostoBodegaByH { get; set; }
        public virtual DbSet<VPlanSemanalCargado> VPlanSemanalCargado { get; set; }
        public virtual DbSet<VPlanSemanalCargado_Yves> VPlanSemanalCargado_Yves { get; set; }
    }
}
