//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanSemanalDetalle
    {
        public int PlanSemanal_Id { get; set; }
        public string PlanSemanal_DiaSemana { get; set; }
        public int Sucursal_Id { get; set; }
        public System.DateTime PlanSemanal_Horario { get; set; }
        public int ObjetivoVisita_Id { get; set; }
    
        public virtual ObjetivoVisita ObjetivoVisita { get; set; }
        public virtual PlanSemanal PlanSemanal { get; set; }
    }
}
