//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanVisita
    {
        public int PlanVisita_Id { get; set; }
        public string PlanVisita_Periodo { get; set; }
        public int Vendedor_Id { get; set; }
        public int Sucursal_Id { get; set; }
        public string PlanVisita_DiaSemana { get; set; }
        public int PlanVisita_NroSemana { get; set; }
        public System.DateTime PlanVisita_Horario { get; set; }
        public int ObjetivoVisita_Id { get; set; }
        public System.DateTime PlanVisita_FechaCreacion { get; set; }
        public System.DateTime PlanVisita_FechaLastUpdate { get; set; }
    
        public virtual ObjetivoVisita ObjetivoVisita { get; set; }
    }
}
