//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanSemanal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanSemanal()
        {
            this.PlanSemanalDetalles = new HashSet<PlanSemanalDetalle>();
        }
    
        public int PlanSemanal_Id { get; set; }
        public string PlanSemanal_Periodo { get; set; }
        public int PlanSemanal_NroSemana { get; set; }
        public int Vendedor_Id { get; set; }
        public string PlanSemanal_Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanSemanalDetalle> PlanSemanalDetalles { get; set; }
    }
}
