//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PLAN_VISITAEntities : DbContext
    {
        public PLAN_VISITAEntities()
            : base("name=PLAN_VISITAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bi_project> bi_project { get; set; }
        public virtual DbSet<bi_salary_survey> bi_salary_survey { get; set; }
        public virtual DbSet<bi_sales> bi_sales { get; set; }
        public virtual DbSet<CategoryPlanVisita> CategoryPlanVisita { get; set; }
        public virtual DbSet<CategoryPlanVisitaRelation> CategoryPlanVisitaRelation { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Division> Division { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<EstadoMotivo> EstadoMotivo { get; set; }
        public virtual DbSet<GXDEVICERESULT> GXDEVICERESULT { get; set; }
        public virtual DbSet<GXPARAMETERS> GXPARAMETERS { get; set; }
        public virtual DbSet<GXRESULTROWS> GXRESULTROWS { get; set; }
        public virtual DbSet<JefeVentas> JefeVentas { get; set; }
        public virtual DbSet<LocationHistory> LocationHistory { get; set; }
        public virtual DbSet<Motivo> Motivo { get; set; }
        public virtual DbSet<Notificacion> Notificacion { get; set; }
        public virtual DbSet<ObjetivoVisita> ObjetivoVisita { get; set; }
        public virtual DbSet<PlanAccion> PlanAccion { get; set; }
        public virtual DbSet<PlanSemanal> PlanSemanal { get; set; }
        public virtual DbSet<PlanSemanalDetalle> PlanSemanalDetalle { get; set; }
        public virtual DbSet<PlanVisita> PlanVisita { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Sucursal> Sucursal { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tarea> Tarea { get; set; }
        public virtual DbSet<Task> Task { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Vendedor> Vendedor { get; set; }
        public virtual DbSet<VendedorCliente> VendedorCliente { get; set; }
        public virtual DbSet<VendedorZona> VendedorZona { get; set; }
        public virtual DbSet<Venta> Venta { get; set; }
        public virtual DbSet<VentaLinea> VentaLinea { get; set; }
        public virtual DbSet<Visita> Visita { get; set; }
        public virtual DbSet<VisitaDual> VisitaDual { get; set; }
        public virtual DbSet<Zona> Zona { get; set; }
        public virtual DbSet<ZonaSucursal> ZonaSucursal { get; set; }
        public virtual DbSet<JDT1> JDT1 { get; set; }
        public virtual DbSet<OACT> OACT { get; set; }
        public virtual DbSet<OJDT> OJDT { get; set; }
        public virtual DbSet<entradadeposito> entradadeposito { get; set; }
        public virtual DbSet<entradadepositodetalle> entradadepositodetalle { get; set; }
        public virtual DbSet<GXA0021> GXA0021 { get; set; }
        public virtual DbSet<MSreplication_objects> MSreplication_objects { get; set; }
        public virtual DbSet<MSreplication_subscriptions> MSreplication_subscriptions { get; set; }
        public virtual DbSet<MSsubscription_agents> MSsubscription_agents { get; set; }
        public virtual DbSet<trazaproceso> trazaproceso { get; set; }
        public virtual DbSet<Detalle_Visita> Detalle_Visita { get; set; }
        public virtual DbSet<V_CARTERA_ACTUAL> V_CARTERA_ACTUAL { get; set; }
        public virtual DbSet<V_Cartera_Clientes> V_Cartera_Clientes { get; set; }
        public virtual DbSet<V_CLIENTE_SUCURSAL> V_CLIENTE_SUCURSAL { get; set; }
        public virtual DbSet<V_Clientes_HBF> V_Clientes_HBF { get; set; }
        public virtual DbSet<V_Clientes_Total> V_Clientes_Total { get; set; }
        public virtual DbSet<V_ClientesVenRep> V_ClientesVenRep { get; set; }
        public virtual DbSet<V_Detalle_Visita> V_Detalle_Visita { get; set; }
        public virtual DbSet<V_Dual_Visita> V_Dual_Visita { get; set; }
        public virtual DbSet<V_PLAN_SEMANAL> V_PLAN_SEMANAL { get; set; }
        public virtual DbSet<V_RUTA_DIA> V_RUTA_DIA { get; set; }
        public virtual DbSet<V_RUTA_DIA_NUEVO> V_RUTA_DIA_NUEVO { get; set; }
        public virtual DbSet<V_VDetallePlanSVendedores> V_VDetallePlanSVendedores { get; set; }
        public virtual DbSet<V_Visitas_Detalle> V_Visitas_Detalle { get; set; }
        public virtual DbSet<V_Visitas_Dual> V_Visitas_Dual { get; set; }
        public virtual DbSet<VCoberturaVendedor> VCoberturaVendedor { get; set; }
        public virtual DbSet<VFrecuenciaVendedorCliente> VFrecuenciaVendedorCliente { get; set; }
        public virtual DbSet<VNotifCostoBodegaByH> VNotifCostoBodegaByH { get; set; }
        public virtual DbSet<VPlanSemanalCargado> VPlanSemanalCargado { get; set; }
        public virtual DbSet<VPlanSemanalCargado_Yves> VPlanSemanalCargado_Yves { get; set; }
    }
}
