//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanAccion
    {
        public int PlanAccion_Id { get; set; }
        public string PlanAccion_Analisis { get; set; }
        public string PlanAccion_Descripcion { get; set; }
        public string PlanAccion_Responsable { get; set; }
        public System.DateTime PlanAccion_FechaComp { get; set; }
        public string PlanAccion_Estado { get; set; }
        public System.DateTime PlanAccion_FechaCreacion { get; set; }
        public System.DateTime planAccion_FechaLastUpdate { get; set; }
        public short PlandeVisita { get; set; }
    }
}
