//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanVisita
    {
        public int PlanVisita_Id { get; set; }
        public string PlanVisita_Periodo { get; set; }
        public int Vendedor_Id { get; set; }
        public int Sucursal_Id { get; set; }
        public string PlanVisita_DiaSemana { get; set; }
        public int PlanVisita_NroSemana { get; set; }
        public System.DateTime PlanVisita_Horario { get; set; }
        public int ObjetivoVisita_Id { get; set; }
        public System.DateTime PlanVisita_FechaCreacion { get; set; }
        public System.DateTime PlanVisita_FechaLastUpdate { get; set; }
    
        public virtual ObjetivoVisita ObjetivoVisita { get; set; }
    }
}
