//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.VentaLineas = new HashSet<VentaLinea>();
        }
    
        public int Producto_Id { get; set; }
        public string Producto_Descripcion { get; set; }
        public string Producto_Marca { get; set; }
        public System.DateTime Producto_FechaCreacion { get; set; }
        public System.DateTime Producto_FechaLastUpdate { get; set; }
        public Nullable<decimal> Producto_Precio { get; set; }
        public string Producto_Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentaLinea> VentaLineas { get; set; }
    }
}
