//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.VentaLineas = new HashSet<VentaLinea>();
        }
    
        public int Producto_Id { get; set; }
        public string Producto_Descripcion { get; set; }
        public string Producto_Marca { get; set; }
        public System.DateTime Producto_FechaCreacion { get; set; }
        public System.DateTime Producto_FechaLastUpdate { get; set; }
        public Nullable<decimal> Producto_Precio { get; set; }
        public string Producto_Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentaLinea> VentaLineas { get; set; }
    }
}
