//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puntera
    {
        public int Puntera_Id { get; set; }
        public int Usuario_Id { get; set; }
        public int Marca_Id { get; set; }
        public int SubMarca_Id { get; set; }
        public System.DateTime Puntera_FechaCarga { get; set; }
        public int Puntera_Cantidad { get; set; }
        public bool Puntera_LucesEncendidas { get; set; }
        public string Puntera_Observacion { get; set; }
    
        public virtual Marcas Marcas { get; set; }
        public virtual SubMarca SubMarca { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
