//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarea
    {
        public int Tarea_Id { get; set; }
        public string Tarea_Nombre { get; set; }
        public System.DateTime Tarea_FechaLastUpdate { get; set; }
        public System.DateTime Tarea_FechaCreacion { get; set; }
    }
}
