//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarea
    {
        public int Tarea_Id { get; set; }
        public string Tarea_Nombre { get; set; }
        public System.DateTime Tarea_FechaLastUpdate { get; set; }
        public System.DateTime Tarea_FechaCreacion { get; set; }
    }
}
