//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class trazaproceso
    {
        public int TrazaProcesoId { get; set; }
        public System.DateTime TrazaProcesoFecha { get; set; }
        public string TrazaProcesoDescripcion { get; set; }
        public string TrazaProcesoBarCode { get; set; }
        public string TrazaProcesoItemCode { get; set; }
        public string TrazaProcesoLote { get; set; }
        public string TrazaProcesoNextBarCode { get; set; }
        public string TrazaProcesoBaseBarCode { get; set; }
        public System.DateTime TrazaProcesoExpDate { get; set; }
        public string TrazaProcesoItemName { get; set; }
        public string TrazaProcesoUser { get; set; }
        public int ProcesoId { get; set; }
        public int TrazaProcesoDocNum { get; set; }
        public decimal TrazaProcesoCantidad { get; set; }
    }
}
