//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicacion
    {
        public int Ubicacion_Id { get; set; }
        public int Sucursal_Id { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
    
        public virtual Sucursal Sucursal { get; set; }
    }
}
