//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Usuario_Id { get; set; }
        public string Usuario_Nombre { get; set; }
        public string Usuario_Pass { get; set; }
        public int JefeVentas_Id { get; set; }
        public string Usuario1 { get; set; }
        public Nullable<int> Usuario_Vendedor_Id { get; set; }
    
        public virtual JefeVenta JefeVenta { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
