//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Cartera_Clientes
    {
        public string Visitador { get; set; }
        public string Cod__de_Cliente { get; set; }
        public string Cliente { get; set; }
        public string Direccion { get; set; }
        public string Ciudad { get; set; }
        public int Cod_Sucursal { get; set; }
        public Nullable<int> Frecuencia_de_Visita { get; set; }
        public string Periodo { get; set; }
    }
}
