//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Cartera_Clientes
    {
        public string Visitador { get; set; }
        public string Cod__de_Cliente { get; set; }
        public string Cliente { get; set; }
        public string Direccion { get; set; }
        public string Ciudad { get; set; }
        public int Cod_Sucursal { get; set; }
        public Nullable<int> Frecuencia_de_Visita { get; set; }
        public string Periodo { get; set; }
    }
}
