//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CARTERA_ACTUAL
    {
        public short Vendedor_Id { get; set; }
        public int Sucursal_Id { get; set; }
        public short Cantidad_Visitas { get; set; }
        public Nullable<decimal> Promedio_Ventas { get; set; }
        public string Vendedor_Nombre { get; set; }
        public string Cliente_RazonSocial { get; set; }
        public string Sucursal_Direccion { get; set; }
        public string Sucursal_Ciudad { get; set; }
        public int Expr1 { get; set; }
        public int JefeVentas_Id { get; set; }
        public string JefeVentas_Nombre { get; set; }
    }
}
