//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CARTERA_ACTUAL
    {
        public short Vendedor_Id { get; set; }
        public int Sucursal_Id { get; set; }
        public short Cantidad_Visitas { get; set; }
        public Nullable<decimal> Promedio_Ventas { get; set; }
        public string Vendedor_Nombre { get; set; }
        public string Cliente_RazonSocial { get; set; }
        public string Sucursal_Direccion { get; set; }
        public string Sucursal_Ciudad { get; set; }
        public int Expr1 { get; set; }
        public int JefeVentas_Id { get; set; }
        public string JefeVentas_Nombre { get; set; }
    }
}
