//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ClientesVenRep
    {
        public int Vendedor_Id { get; set; }
        public string Vendedor { get; set; }
        public string Vendedor_Rol { get; set; }
        public int JefeVentas_Id { get; set; }
        public string JefeDeVentas { get; set; }
        public int Sucursal_Id { get; set; }
        public int Cantidad_Visitas { get; set; }
        public string ClienteSAP { get; set; }
        public string Sucursal_Ciudad { get; set; }
        public string Sucursal_Direccion { get; set; }
        public string Cliente_RazonSocial { get; set; }
    }
}
