//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ClientesVenRep
    {
        public int Vendedor_Id { get; set; }
        public string Vendedor { get; set; }
        public string Vendedor_Rol { get; set; }
        public int JefeVentas_Id { get; set; }
        public string JefeDeVentas { get; set; }
        public int Sucursal_Id { get; set; }
        public int Cantidad_Visitas { get; set; }
        public string ClienteSAP { get; set; }
        public string Sucursal_Ciudad { get; set; }
        public string Sucursal_Direccion { get; set; }
        public string Cliente_RazonSocial { get; set; }
    }
}
