//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Clientes_HBF
    {
        public Nullable<long> Fila { get; set; }
        public string cardcode { get; set; }
        public string cardfname { get; set; }
        public string Address { get; set; }
        public string city { get; set; }
        public string street { get; set; }
    }
}
