//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CLIENTE_SUCURSAL
    {
        public string Cliente_Cod { get; set; }
        public string Cliente_RazonSocial { get; set; }
        public string Sucursal_Ciudad { get; set; }
        public string Sucursal_Direccion { get; set; }
    }
}
