//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Clientes_HBF
    {
        public Nullable<long> Fila { get; set; }
        public string cardcode { get; set; }
        public string cardfname { get; set; }
        public string Address { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public Nullable<short> GroupCode { get; set; }
        public string GroupName { get; set; }
        public string Address2 { get; set; }
    }
}
