//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Dual_Visita
    {
        public System.Guid VisitaDual_Id { get; set; }
        public string Periodo { get; set; }
        public System.DateTime VisitaDual_Fecha { get; set; }
        public string Visita_Hora_Entrada { get; set; }
        public string Visita_Hora_Salida { get; set; }
        public string Visitador { get; set; }
        public string Cliente { get; set; }
        public string Ciudad { get; set; }
        public int SucursalId { get; set; }
        public string Dirección { get; set; }
        public string Observacion { get; set; }
        public int Cantidad { get; set; }
        public string Ubicacion { get; set; }
    }
}
