//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PlanSemCargXDia
    {
        public string NombreVendedor { get; set; }
        public int NroSemana { get; set; }
        public string Periodo { get; set; }
        public string NombreJefe { get; set; }
        public int LUNES { get; set; }
        public int MARTES { get; set; }
        public int MIERCOLES { get; set; }
        public int JUEVES { get; set; }
        public int VIERNES { get; set; }
    }
}
