//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PlanSemCargXDia
    {
        public string NombreVendedor { get; set; }
        public int NroSemana { get; set; }
        public string Periodo { get; set; }
        public string NombreJefe { get; set; }
        public int LUNES { get; set; }
        public int MARTES { get; set; }
        public int MIERCOLES { get; set; }
        public int JUEVES { get; set; }
        public int VIERNES { get; set; }
    }
}
