//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RUTA_DIA
    {
        public string Periodo { get; set; }
        public string Visitador { get; set; }
        public int JefeVentas_Id { get; set; }
        public string Cliente { get; set; }
        public string Direccion { get; set; }
        public string DiaSemana { get; set; }
        public int NroSemana { get; set; }
        public string HoraEntrada { get; set; }
        public string Objetivo { get; set; }
        public string Fecha { get; set; }
    }
}
