//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Visitas_Detalle
    {
        public int Visita_Id { get; set; }
        public string Periodo { get; set; }
        public System.DateTime Visita_fecha { get; set; }
        public string Dia { get; set; }
        public string Mes { get; set; }
        public Nullable<int> Año { get; set; }
        public string Visita_Hora { get; set; }
        public string Vendedor { get; set; }
        public int Vendedor_Id { get; set; }
        public string Division { get; set; }
        public string CodCliente { get; set; }
        public string Cliente { get; set; }
        public string Ciudad { get; set; }
        public string Dirección { get; set; }
        public string Resultado_de_Visita { get; set; }
        public string Motivo { get; set; }
        public string Observacion { get; set; }
        public string Análisis { get; set; }
        public string Plan_de_Acción { get; set; }
        public string Responsable { get; set; }
        public Nullable<System.DateTime> Fecha_de_Compromiso { get; set; }
        public string Plan_de_Acción_Estado { get; set; }
        public int Cantidad { get; set; }
        public int SucursalID { get; set; }
        public int frecuencia { get; set; }
    }
}
