//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VClienteSAPHBF
    {
        public string CodigoCliente { get; set; }
        public string RazonSocial { get; set; }
        public string NombreFantasia { get; set; }
        public string RUC { get; set; }
        public string CodSucursal { get; set; }
        public string Direccion { get; set; }
        public string Localidad { get; set; }
        public string Departamento { get; set; }
        public string U_TipoCliente { get; set; }
        public string Telefono { get; set; }
        public string Estado { get; set; }
        public string U_ClasifClientDPP { get; set; }
        public string Empresa { get; set; }
    }
}
