//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VClienteSAPHBF
    {
        public string CodigoCliente { get; set; }
        public string RazonSocial { get; set; }
        public string NombreFantasia { get; set; }
        public string RUC { get; set; }
        public string CodSucursal { get; set; }
        public string Direccion { get; set; }
        public string Localidad { get; set; }
        public string Departamento { get; set; }
        public string U_TipoCliente { get; set; }
        public string Telefono { get; set; }
        public string Estado { get; set; }
        public string U_ClasifClientDPP { get; set; }
        public string Empresa { get; set; }
    }
}
