//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VencimientoProductoDetalle
    {
        public int VencimientoProductoDetalle_Id { get; set; }
        public int VencimientoProducto_Id { get; set; }
        public string VencimientoProductoDetalle_Codigo_Barras { get; set; }
        public string VencimientoProductoDetalle_Descripcion_Producto { get; set; }
        public System.DateTime VencimientoProductoDetalle_Rango_Fecha { get; set; }
        public string VencimientoProductoDetalle_Cantidad_SKU { get; set; }
    
        public virtual VencimientoProducto VencimientoProducto { get; set; }
    }
}
