//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VencimientoProducto
    {
        public int Vencimiento_Id { get; set; }
        public string Vencimiento_Division { get; set; }
        public string Vencimiento_Canal { get; set; }
        public string Vencimiento_Cargo { get; set; }
        public string Vencimiento_Colaborador { get; set; }
        public string Vencimiento_PuntoVentaDireccion { get; set; }
        public string Vencimiento_Codigo_Barras { get; set; }
        public string Vencimiento_Descripcion_Producto { get; set; }
        public System.DateTime Vencimiento_Rango_Fecha { get; set; }
        public string Vencimiento_Cantidad_SKU { get; set; }
    }
}
