//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendedor()
        {
            this.Usuarios = new HashSet<Usuario>();
            this.VendedorZonas = new HashSet<VendedorZona>();
            this.Canals = new HashSet<Canal>();
        }
    
        public int Vendedor_Id { get; set; }
        public string Vendedor_Nombre { get; set; }
        public int JefeVentas_Id { get; set; }
        public string Vendedor_Mail { get; set; }
        public System.DateTime Vendedor_FechaCreacion { get; set; }
        public System.DateTime Vendedor_FechaLastUpdate { get; set; }
        public string Vendedor_Rol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendedorZona> VendedorZonas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Canal> Canals { get; set; }
    }
}
