//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendedorZona
    {
        public int Vendedor_Id { get; set; }
        public int Zona_Id { get; set; }
        public string VendedorZonaEstado { get; set; }
        public string VendedorZonaPeriodo { get; set; }
    
        public virtual Vendedor Vendedor { get; set; }
        public virtual Zona Zona { get; set; }
    }
}
