//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendedor
    {
        public int Vendedor_Id { get; set; }
        public string Vendedor_Nombre { get; set; }
        public int JefeVentas_Id { get; set; }
        public string Vendedor_Mail { get; set; }
        public System.DateTime Vendedor_FechaCreacion { get; set; }
        public System.DateTime Vendedor_FechaLastUpdate { get; set; }
        public string Vendedor_Rol { get; set; }
    }
}
