//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int Venta_Id { get; set; }
        public System.DateTime Venta_Fecha { get; set; }
        public System.DateTime Venta_Hora { get; set; }
        public short Vendedor_Id { get; set; }
        public string Cliente_Nombre { get; set; }
        public Nullable<decimal> Venta_Total { get; set; }
    }
}
