//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaLinea
    {
        public int Venta_Id { get; set; }
        public short Nro_Linea { get; set; }
        public int Producto_Id { get; set; }
        public string Producto_Comentario { get; set; }
        public int Linea_Cantidad { get; set; }
        public Nullable<decimal> Linea_Total { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
