//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaLinea
    {
        public int Venta_Id { get; set; }
        public short Nro_Linea { get; set; }
        public int Producto_Id { get; set; }
        public string Producto_Comentario { get; set; }
        public int Linea_Cantidad { get; set; }
        public Nullable<decimal> Linea_Total { get; set; }
    }
}
