//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int Venta_Id { get; set; }
        public System.DateTime Venta_Fecha { get; set; }
        public System.DateTime Venta_Hora { get; set; }
        public short Vendedor_Id { get; set; }
        public string Cliente_Nombre { get; set; }
        public Nullable<decimal> Venta_Total { get; set; }
    }
}
