//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VFrecuenciaVendedorCliente
    {
        public int Sucursal_Id { get; set; }
        public Nullable<int> Frecuencia { get; set; }
        public string Vendedor_Nombre { get; set; }
        public int Vendedor_Id { get; set; }
        public int JefeVentas_Id { get; set; }
        public string JefeVentas_Nombre { get; set; }
        public string Sucursal_Ciudad { get; set; }
        public string Periodo { get; set; }
        public string Cliente_Cod { get; set; }
        public string Cliente_RazonSocial { get; set; }
        public int Cantidad { get; set; }
        public Nullable<int> CantidadVisita { get; set; }
        public string Direccion { get; set; }
    }
}
