//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VFrecuenciaVendedorCliente
    {
        public int Sucursal_Id { get; set; }
        public Nullable<int> Frecuencia { get; set; }
        public string Vendedor_Nombre { get; set; }
        public int Vendedor_Id { get; set; }
        public int JefeVentas_Id { get; set; }
        public string JefeVentas_Nombre { get; set; }
        public string Sucursal_Ciudad { get; set; }
        public string Periodo { get; set; }
        public string Cliente_Cod { get; set; }
        public string Cliente_RazonSocial { get; set; }
        public int Cantidad { get; set; }
        public Nullable<int> CantidadVisita { get; set; }
    }
}
