//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitaDual
    {
        public System.Guid VisitaDual_Id { get; set; }
        public int Vendedor_Id { get; set; }
        public int Sucursal_Id { get; set; }
        public System.DateTime VisitaDual_Hora_Entrada { get; set; }
        public string VisitaDual_Ubicacion_Entrada { get; set; }
        public Nullable<System.DateTime> VisitaDual_Hora_Salida { get; set; }
        public string VisitaDual_Ubicacion_Salida { get; set; }
        public System.DateTime VisitaDual_Fecha { get; set; }
        public string VisitaDual_Observacion { get; set; }
    
        public virtual VendedorCliente VendedorCliente { get; set; }
    }
}
