//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitaSAP
    {
        public int Visita_Id { get; set; }
        public int Vendedor_Id { get; set; }
        public int Sucursal_Id { get; set; }
        public string Cliente_Cod { get; set; }
        public System.DateTime Visita_fecha { get; set; }
        public int Estado_Id { get; set; }
        public int Motivo_Id { get; set; }
        public string Visita_Observacion { get; set; }
        public string Visita_Ubicacion_Entrada { get; set; }
        public string Visita_Ubicacion_Salida { get; set; }
        public System.DateTime Visita_Hora_Entrada { get; set; }
        public System.DateTime Visita_Hora_Salida { get; set; }
    }
}
