//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visita
    {
        public int Visita_Id { get; set; }
        public int Vendedor_Id { get; set; }
        public int Sucursal_Id { get; set; }
        public System.DateTime Visita_fecha { get; set; }
        public int Estado_Id { get; set; }
        public int Motivo_Id { get; set; }
        public string Visita_Observacion { get; set; }
        public string Visita_Ubicacion { get; set; }
        public System.DateTime Visita_Hora { get; set; }
    
        public virtual EstadoMotivo EstadoMotivo { get; set; }
        public virtual VendedorCliente VendedorCliente { get; set; }
    }
}
