//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VNotifCostoBodegaByH
    {
        public string EMPRESA { get; set; }
        public string CodigoBodega { get; set; }
        public string NombreBodega { get; set; }
        public Nullable<decimal> CostoBodega { get; set; }
    }
}
