//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPlanSemanalCargado
    {
        public string Visitador { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> NroSemana { get; set; }
        public string JefeVentas { get; set; }
        public string Division { get; set; }
    }
}
