//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VVisitasRealizadas
    {
        public string Vendedor { get; set; }
        public int CodigoVendedor { get; set; }
        public string Periodo { get; set; }
        public string Visita_fecha { get; set; }
        public string Visita_HoraEntrada { get; set; }
        public string Visita_HoraSalida { get; set; }
        public string Dia { get; set; }
        public string CodigoCliente { get; set; }
        public string RazonSocial { get; set; }
        public string Observacion { get; set; }
        public string UbicacionEntrada { get; set; }
        public string UbicacionSalida { get; set; }
    }
}
