//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZonaSucursal
    {
        public int Zona_Id { get; set; }
        public int Sucursal_Id { get; set; }
        public string ZonaSucursalEstado { get; set; }
        public int ZonaSucursalCantidad_Visitas { get; set; }
    
        public virtual Sucursal Sucursal { get; set; }
        public virtual Zona Zona { get; set; }
    }
}
