//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanVisitaWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZonaSucursal
    {
        public int Zona_Id { get; set; }
        public int Sucursal_Id { get; set; }
        public string ZonaSucursalEstado { get; set; }
        public int ZonaSucursalCantidad_Visitas { get; set; }
    
        public virtual Sucursal Sucursal { get; set; }
        public virtual Zona Zona { get; set; }
    }
}
